version: 0.1.0.{build}
branches:
  only:
    - master

image: Visual Studio 2019
platform: x64


clone_folder: C:/projects/juce-6-demo

configuration:
  - Release

install:
  - cd %APPVEYOR_BUILD_FOLDER%
  - git submodule update --init --recursive

build:
  parallel: true

build_script:
  - cd C:/projects/juce-6-demo
  - mkdir build
  - cd build
  - cmake -G "Visual Studio 16 2019" ..
  - cmake --build . --config Release
  - ctest